name: steam_client
description: A client library for getting community and store resources from the Steam Web API.
repository: https://github.com/paoloposo/steam_client

version: 0.1.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  xml: ^4.5.1
  intl: ^0.16.1
  quiver: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
